// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjVOoExwXVX758GJRjo4IZJMCPHbrWe4',
    appId: '1:522150981060:web:41182bffb084afe3c58891',
    messagingSenderId: '522150981060',
    projectId: 'easy-orders-18',
    authDomain: 'easy-orders-18.firebaseapp.com',
    storageBucket: 'easy-orders-18.firebasestorage.app',
    measurementId: 'G-TSGZHMT8RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7mKPEpbqwet2Q2Sw31bnIcVqYpEHjqlE',
    appId: '1:522150981060:android:47a42ccc6393997fc58891',
    messagingSenderId: '522150981060',
    projectId: 'easy-orders-18',
    storageBucket: 'easy-orders-18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0Fes6wKKHq2mpOzz5UvQI1zhzJHVGko',
    appId: '1:522150981060:ios:57e629193bb598e9c58891',
    messagingSenderId: '522150981060',
    projectId: 'easy-orders-18',
    storageBucket: 'easy-orders-18.firebasestorage.app',
    iosBundleId: 'com.example.easyOrders',
  );
}
